services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rooms
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/data/postgres

  redis:
    image: bitnami/redis:latest
    environment:
      - REDIS_PASSWORD=password
    ports:
      - "6379:6379"

  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    networks:
      - default
    ports:
      - "8080:8080"

volumes:
  postgres-db:
